### ISSUE TITLE
solution does not work, gets stuck

### ISSUE THREAD

**Issue by rubo77** [smack42/DriftingDroids#16]
This puzzle is not solved correctly in roboyard 7.1 and 8.1 (8.1 uses your latest solver now)

![Screenshot_20190608-091329_Roboyard](https://user-images.githubusercontent.com/1591563/59144746-70833180-89db-11e9-8a4d-808735727c53.jpg)

It says 4 moves, but gets stuck like this:

![Screenshot_20190608-091335_Roboyard](https://user-images.githubusercontent.com/1591563/59144754-97416800-89db-11e9-881f-88a56628fbb1.jpg)

**Comment by smack42** [comment]
I've copied the game state from your screenshot into DriftingDroids:
```
!DriftingDroids_game!7356AEB8!AAAEL3ja5ZJdCoAwDIPzoeCbCJ7AI/vkda0ypy5T
D2ChoRn9I6skDZu3AVP4GN6FLw29KEzfhmEOSQGXV25lBykGVTmpHBv+HhSzfBWpmooXls
0vKbgKnCJkpNYvC+3c93nQW1RW5lUTbKvf/Td28P8+gJQy7zyQFaqhAts=!
```
It works correctly and find this 4-moves solution:
red: W
green: S W S
![grafik](https://user-images.githubusercontent.com/1110893/59145582-2fdce580-89e6-11e9-8bf2-8da0fd9d05d2.png)

**Comment by smack42** [comment]
Works correctly in latest release version (DriftingDroids 1.3.7) as well.

**Comment by rubo77** [comment]
Then it must have something to do with the other code. 

Moved here: https://github.com/rubo77/Roboyard/issues/9
