### ISSUE TITLE
Solver finds impossible solution

### ISSUE THREAD

**Issue by rubo77** [smack42/DriftingDroids#17]
On this puzzle roboyard thinks it finds a solution with 12:
![ry](https://user-images.githubusercontent.com/1591563/60629126-cee1db00-9df4-11e9-9ca5-7d95023c330c.png)

but when you click on the solve button, it gets stuck after two moves

![signal-2019-07-03-110045](https://user-images.githubusercontent.com/1591563/60629175-fe90e300-9df4-11e9-9d92-45de563929a5.png)

**Comment by rubo77** [comment]
Would it be easy to implement the export function of drifting droids In roboyard?

**Comment by smack42** [comment]
I've copied the game state from your screenshot into DriftingDroids:
```
!DriftingDroids_game!F1586A4C!AAAEL3ja5ZLdDYAgDIT7JcQXH3RGx3AHJ3QZiz8
JHCAD0OQa+nOUCzUzWyOCu8WxOzbHSZgnxKxvvIgeySdV/shISzqYJ6YzvIhaFCXUyjTq
lH0yU59GJr/Cf+ST8fn0UlKySK9GxNHRS7NzkP+mtvADL8CbOu6Tey6k+gPJ!
```
It works correctly and finds several 14-moves solutions.

**Comment by smack42** [comment]
The code that loads and saves the game state using this text format is implemented in:
```
class Board
public static Board createBoardGameDump(final String dump)
public String getGameDump()
```
