### ISSUE TITLE
some automatic code cleanup

### ISSUE THREAD

**Issue by rubo77** [smack42/DriftingDroids#21]
I ran the automatic code cleanup in Android Studio, and it found these changes:

https://github.com/rubo77/Roboyard/commit/e1dac9e6edd6c7825b0c27a506cdf4f21d7e10e4

**Comment by rubo77** [comment]
And these changes will enhance performance:

https://github.com/rubo77/Roboyard/commit/9f41ed5699c74fa60ac89e2b731c619fb36f0c02

**Comment by rubo77** [comment]
And some more minor changes:

https://github.com/rubo77/Roboyard/commit/608d5da39f49d11e94da2a5c4e297140443637e3

**Comment by smack42** [comment]
I've integrated most of these changes, however I did not merge these:
- access modifiers (public, private, etc) - why should they be changed?
- autoboxing / unboxing - I don't want to use this feature, because it can cause hidden performance problems
