### ISSUE TITLE
javadoc doesn't reflect the parameters

### ISSUE THREAD

**Issue by rubo77** [smack42/DriftingDroids#22]
https://github.com/smack42/DriftingDroids/blob/a97d03f743a8026a70c139b0f10d70fa6b84f337/src/driftingdroids/model/KeyTrieSet.java#L63

**Comment by rubo77** [comment]
There is only one parameter `board`, it seems like the doc is an old relict

**Comment by smack42** [comment]
Thank you! Yes these things happen when code is changed. When the code is not a public API that many people use, then such Javadoc mistakes remain unnoticed...
