### ISSUE TITLE
Start.jar doesn't work on Ubuntu 21.04 with openjdk 11

### ISSUE THREAD

**Issue by rubo77** [smack42/DriftingDroids#23]
```
java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode, sharing)

$ ./start.jar 
invalid file (bad magic number): Exec format error

$ java ./start.jar
Error: Could not find or load main class ..start.jar
Caused by: java.lang.ClassNotFoundException: //start/jar

**Comment by rubo77** [comment]
I tried downloading the latest Java SE Development Kit 17.0.1 from https://www.oracle.com/java/technologies/downloads/ and installing via 

    sudo apt install libc6-x32
    sudo dpkg -i jdk-17_linux-x64_bin.deb

starting with java 17 gives the same error:

```
$ java17 ./start.jar 
Error: Could not find or load main class ..start.jar
Caused by: java.lang.ClassNotFoundException: //start/jar

**Comment by smack42** [comment]
Please use this command:
`java -jar start.jar`

By the way, this `start.jar` is the compiled program "appstart":  https://github.com/smack42/appstart

**Comment by rubo77** [comment]
When I try with `-jar` just nothing happens:

    $ java -jar start.jar 
    $ _ 


Now I tried

    sudo apt-get install advancecomp
    ./buildjar.sh 

Which runs until this error:

    Error: Unable to access jarfile /home/ruben/Programme/proguard6.2/lib/proguard.jar

**Comment by rubo77** [comment]
strange, that, if I edit SwingGUI.java, I still get the same error, as if it was still the old file somehow cached or so ;?

**Comment by rubo77** [comment]
```
$ java -Dappstart.verbose=true -jar start.jar
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: using java in /usr/lib/jvm/java-11-openjdk-amd64/bin
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: appstart dir: /var/www/DriftingDroids
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: launched from start.jar
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: look for application specific config file: start.properties
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: libs dir: /var/www/DriftingDroids/lib
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: classpath = /var/www/DriftingDroids:/var/www/DriftingDroids/lib/designgridlayout-1.11.jar:/var/www/DriftingDroids/lib/flatlaf-0.45-sources.jar:/var/www/DriftingDroids/lib/designgridlayout-1.11-sources.jar:/var/www/DriftingDroids/lib/flatlaf-0.45.jar:
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: vmoptions = -Xmx800M
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: main class = driftingdroids.ui.Starter
Dez. 12, 2021 3:01:55 NACHM. org.appstart.Starter main
INFORMATION: command line:
[/usr/lib/jvm/java-11-openjdk-amd64/bin/java, -Xmx800M, -Dapp.vm.options=-Xmx800M, -Dapp.main.class=driftingdroids.ui.Starter, -Dswing.defaultlaf=com.formdev.flatlaf.FlatIntelliJLaf, -cp, /var/www/DriftingDroids:/var/www/DriftingDroids/lib/designgridlayout-1.11.jar:/var/www/DriftingDroids/lib/flatlaf-0.45-sources.jar:/var/www/DriftingDroids/lib/designgridlayout-1.11-sources.jar:/var/www/DriftingDroids/lib/flatlaf-0.45.jar:, driftingdroids.ui.Starter]

**Comment by smack42** [comment]
Yes, since release 1.3.9 the program requires Java 8 to build and Java 8+ to run.
https://github.com/smack42/DriftingDroids/releases/tag/1.3.9

I never use this script `compilerun.sh` myself. I build and run the program in Eclipse and only use `buildjar.sh` when I build a release package.

**Comment by smack42** [comment]
I have now fixed and simplified the build script (ProGuard and advzip are not used anymore) and also updated README-developer.txt

**Comment by rubo77** [comment]
java-11-openjdk is Not Java 8+ ?

**Comment by smack42** [comment]
Yes, java-11-openjdk is Java 8+

Appstart and DriftingDroids work fine with Java 8 and 11 on my Linux system.
I tested them some time ago on Windows as well, with Java 8, 11 and 17 (or 16? don't remember)

**Comment by rubo77** [comment]
still the app doesn't start with 

    java -jar start.jar

but this works:

    ./compilerun.sh

**Comment by smack42** [comment]
Please use these commands:
```
./compilerun.sh   (and then quit DriftingDroids)
./buildrelease.sh
cd DriftingDroids_release
java -jar start.jar
```

**Comment by rubo77** [comment]
This works.

it seems like since *.jar is in .gitignore, the start.jar in the root folder of the repository is not updated

**Comment by smack42** [comment]
`start.jar` just needs `appstart.properties` in the same folder and the program components (jar files) in sub-folder `lib`.

IMO we don't need more documentation on how to launch the program.

**Users** download a release package from https://github.com/smack42/DriftingDroids/releases, then they unzip it, have a look at `README.txt` and find that they just need to doubleclick on `start.jar`. If they are really curious they can find more information in the user documentation.

**Developers** probably clone the entire Git repository and may have a look at `README-developer.txt` to get some initial information.
