### ISSUE TITLE
1 mover bug

### ISSUE THREAD

**Issue by chris0804** [smack42/DriftingDroids#6]
I would like to say that I really like DriftingDroids.  Of all the Ricochet Robot solvers I used, it is by far the best for practice.

I would like to report a bug for version 1.3.3.  For the game, 679C+52+2E21860FBF+C6 , the best solution is 1 move but your program calculated 4 moves.  This bug seems to happen to most games where solution is 1 move.  The same bug also happens to games like, 679C+52+2E21860FA6+C6 .

**Comment by rubo77** [comment]
is it possible to deactivate this "feature" in Roboyard?

**Comment by smack42** [comment]
> is it possible to deactivate this "feature" in Roboyard?

What do you mean? There were two bugfixes to solve this issue.

**Comment by rubo77** [comment]
I would like to show the answer "1 move needed" in roboyard

**Comment by smack42** [comment]
You can call method `isSolution01()` in class `Board` to get this information.

**Comment by rubo77** [comment]
great, I added it here: [7e46fa0c74f61618d2125d3e0d985cbf8a4ff590](https://github.com/Eastcoast-Laboratories/Roboyard/commit/7e46fa0c74f61618d2125d3e0d985cbf8a4ff590#r152944381)
